name: alias_proto
description: Compiled proto files for dart language.
version: 0.0.0
homepage: https://github.com/knightpp/alias-proto

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  protobuf: any
