// Code generated by mockery v2.27.1. DO NOT EDIT.

package gamesvc

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"
)

// MockGameService_JoinClient is an autogenerated mock type for the GameService_JoinClient type
type MockGameService_JoinClient struct {
	mock.Mock
}

type MockGameService_JoinClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGameService_JoinClient) EXPECT() *MockGameService_JoinClient_Expecter {
	return &MockGameService_JoinClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function with given fields:
func (_m *MockGameService_JoinClient) CloseSend() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGameService_JoinClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type MockGameService_JoinClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *MockGameService_JoinClient_Expecter) CloseSend() *MockGameService_JoinClient_CloseSend_Call {
	return &MockGameService_JoinClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *MockGameService_JoinClient_CloseSend_Call) Run(run func()) *MockGameService_JoinClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGameService_JoinClient_CloseSend_Call) Return(_a0 error) *MockGameService_JoinClient_CloseSend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGameService_JoinClient_CloseSend_Call) RunAndReturn(run func() error) *MockGameService_JoinClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function with given fields:
func (_m *MockGameService_JoinClient) Context() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockGameService_JoinClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockGameService_JoinClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockGameService_JoinClient_Expecter) Context() *MockGameService_JoinClient_Context_Call {
	return &MockGameService_JoinClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockGameService_JoinClient_Context_Call) Run(run func()) *MockGameService_JoinClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGameService_JoinClient_Context_Call) Return(_a0 context.Context) *MockGameService_JoinClient_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGameService_JoinClient_Context_Call) RunAndReturn(run func() context.Context) *MockGameService_JoinClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function with given fields:
func (_m *MockGameService_JoinClient) Header() (metadata.MD, error) {
	ret := _m.Called()

	var r0 metadata.MD
	var r1 error
	if rf, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameService_JoinClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockGameService_JoinClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockGameService_JoinClient_Expecter) Header() *MockGameService_JoinClient_Header_Call {
	return &MockGameService_JoinClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *MockGameService_JoinClient_Header_Call) Run(run func()) *MockGameService_JoinClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGameService_JoinClient_Header_Call) Return(_a0 metadata.MD, _a1 error) *MockGameService_JoinClient_Header_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameService_JoinClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *MockGameService_JoinClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function with given fields:
func (_m *MockGameService_JoinClient) Recv() (*Message, error) {
	ret := _m.Called()

	var r0 *Message
	var r1 error
	if rf, ok := ret.Get(0).(func() (*Message, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Message)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGameService_JoinClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type MockGameService_JoinClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *MockGameService_JoinClient_Expecter) Recv() *MockGameService_JoinClient_Recv_Call {
	return &MockGameService_JoinClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *MockGameService_JoinClient_Recv_Call) Run(run func()) *MockGameService_JoinClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGameService_JoinClient_Recv_Call) Return(_a0 *Message, _a1 error) *MockGameService_JoinClient_Recv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGameService_JoinClient_Recv_Call) RunAndReturn(run func() (*Message, error)) *MockGameService_JoinClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *MockGameService_JoinClient) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGameService_JoinClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockGameService_JoinClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockGameService_JoinClient_Expecter) RecvMsg(m interface{}) *MockGameService_JoinClient_RecvMsg_Call {
	return &MockGameService_JoinClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockGameService_JoinClient_RecvMsg_Call) Run(run func(m interface{})) *MockGameService_JoinClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockGameService_JoinClient_RecvMsg_Call) Return(_a0 error) *MockGameService_JoinClient_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGameService_JoinClient_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *MockGameService_JoinClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *MockGameService_JoinClient) Send(_a0 *Message) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Message) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGameService_JoinClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockGameService_JoinClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *Message
func (_e *MockGameService_JoinClient_Expecter) Send(_a0 interface{}) *MockGameService_JoinClient_Send_Call {
	return &MockGameService_JoinClient_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockGameService_JoinClient_Send_Call) Run(run func(_a0 *Message)) *MockGameService_JoinClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Message))
	})
	return _c
}

func (_c *MockGameService_JoinClient_Send_Call) Return(_a0 error) *MockGameService_JoinClient_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGameService_JoinClient_Send_Call) RunAndReturn(run func(*Message) error) *MockGameService_JoinClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *MockGameService_JoinClient) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGameService_JoinClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockGameService_JoinClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockGameService_JoinClient_Expecter) SendMsg(m interface{}) *MockGameService_JoinClient_SendMsg_Call {
	return &MockGameService_JoinClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockGameService_JoinClient_SendMsg_Call) Run(run func(m interface{})) *MockGameService_JoinClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockGameService_JoinClient_SendMsg_Call) Return(_a0 error) *MockGameService_JoinClient_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGameService_JoinClient_SendMsg_Call) RunAndReturn(run func(interface{}) error) *MockGameService_JoinClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function with given fields:
func (_m *MockGameService_JoinClient) Trailer() metadata.MD {
	ret := _m.Called()

	var r0 metadata.MD
	if rf, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}

	return r0
}

// MockGameService_JoinClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type MockGameService_JoinClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *MockGameService_JoinClient_Expecter) Trailer() *MockGameService_JoinClient_Trailer_Call {
	return &MockGameService_JoinClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *MockGameService_JoinClient_Trailer_Call) Run(run func()) *MockGameService_JoinClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGameService_JoinClient_Trailer_Call) Return(_a0 metadata.MD) *MockGameService_JoinClient_Trailer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGameService_JoinClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *MockGameService_JoinClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockGameService_JoinClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockGameService_JoinClient creates a new instance of MockGameService_JoinClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGameService_JoinClient(t mockConstructorTestingTNewMockGameService_JoinClient) *MockGameService_JoinClient {
	mock := &MockGameService_JoinClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
