// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: login_service/login_service.proto

package loginsvc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginGuestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email *string `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
}

func (x *LoginGuestRequest) Reset() {
	*x = LoginGuestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_service_login_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginGuestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGuestRequest) ProtoMessage() {}

func (x *LoginGuestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_login_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGuestRequest.ProtoReflect.Descriptor instead.
func (*LoginGuestRequest) Descriptor() ([]byte, []int) {
	return file_login_service_login_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoginGuestRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginGuestRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type LoginGuestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginGuestResponse) Reset() {
	*x = LoginGuestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_service_login_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginGuestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGuestResponse) ProtoMessage() {}

func (x *LoginGuestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_login_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGuestResponse.ProtoReflect.Descriptor instead.
func (*LoginGuestResponse) Descriptor() ([]byte, []int) {
	return file_login_service_login_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginGuestResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_login_service_login_service_proto protoreflect.FileDescriptor

var file_login_service_login_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0x4c, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x22, 0x2a, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x61, 0x0a, 0x0c,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0a,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6e,
	0x69, 0x67, 0x68, 0x74, 0x70, 0x70, 0x2f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x2d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x76, 0x63, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_login_service_login_service_proto_rawDescOnce sync.Once
	file_login_service_login_service_proto_rawDescData = file_login_service_login_service_proto_rawDesc
)

func file_login_service_login_service_proto_rawDescGZIP() []byte {
	file_login_service_login_service_proto_rawDescOnce.Do(func() {
		file_login_service_login_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_login_service_login_service_proto_rawDescData)
	})
	return file_login_service_login_service_proto_rawDescData
}

var file_login_service_login_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_login_service_login_service_proto_goTypes = []interface{}{
	(*LoginGuestRequest)(nil),  // 0: login_service.LoginGuestRequest
	(*LoginGuestResponse)(nil), // 1: login_service.LoginGuestResponse
}
var file_login_service_login_service_proto_depIdxs = []int32{
	0, // 0: login_service.LoginService.LoginGuest:input_type -> login_service.LoginGuestRequest
	1, // 1: login_service.LoginService.LoginGuest:output_type -> login_service.LoginGuestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_service_login_service_proto_init() }
func file_login_service_login_service_proto_init() {
	if File_login_service_login_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_login_service_login_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginGuestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_service_login_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginGuestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_login_service_login_service_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_login_service_login_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_login_service_login_service_proto_goTypes,
		DependencyIndexes: file_login_service_login_service_proto_depIdxs,
		MessageInfos:      file_login_service_login_service_proto_msgTypes,
	}.Build()
	File_login_service_login_service_proto = out.File
	file_login_service_login_service_proto_rawDesc = nil
	file_login_service_login_service_proto_goTypes = nil
	file_login_service_login_service_proto_depIdxs = nil
}
