// Code generated by mockery v2.27.1. DO NOT EDIT.

package loginsvc

import mock "github.com/stretchr/testify/mock"

// MockUnsafeLoginServiceServer is an autogenerated mock type for the UnsafeLoginServiceServer type
type MockUnsafeLoginServiceServer struct {
	mock.Mock
}

type MockUnsafeLoginServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeLoginServiceServer) EXPECT() *MockUnsafeLoginServiceServer_Expecter {
	return &MockUnsafeLoginServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedLoginServiceServer provides a mock function with given fields:
func (_m *MockUnsafeLoginServiceServer) mustEmbedUnimplementedLoginServiceServer() {
	_m.Called()
}

// MockUnsafeLoginServiceServer_mustEmbedUnimplementedLoginServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedLoginServiceServer'
type MockUnsafeLoginServiceServer_mustEmbedUnimplementedLoginServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedLoginServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeLoginServiceServer_Expecter) mustEmbedUnimplementedLoginServiceServer() *MockUnsafeLoginServiceServer_mustEmbedUnimplementedLoginServiceServer_Call {
	return &MockUnsafeLoginServiceServer_mustEmbedUnimplementedLoginServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedLoginServiceServer")}
}

func (_c *MockUnsafeLoginServiceServer_mustEmbedUnimplementedLoginServiceServer_Call) Run(run func()) *MockUnsafeLoginServiceServer_mustEmbedUnimplementedLoginServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeLoginServiceServer_mustEmbedUnimplementedLoginServiceServer_Call) Return() *MockUnsafeLoginServiceServer_mustEmbedUnimplementedLoginServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeLoginServiceServer_mustEmbedUnimplementedLoginServiceServer_Call) RunAndReturn(run func()) *MockUnsafeLoginServiceServer_mustEmbedUnimplementedLoginServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockUnsafeLoginServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnsafeLoginServiceServer creates a new instance of MockUnsafeLoginServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnsafeLoginServiceServer(t mockConstructorTestingTNewMockUnsafeLoginServiceServer) *MockUnsafeLoginServiceServer {
	mock := &MockUnsafeLoginServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
